name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Enhancements'
    labels:
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'crash'
      - 'bug'
  - title: 'Others'
    labels:
      - 'chore'
      - 'modularization'
exclude-labels:
  - 'release'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  # Release details

  $CHANGES
