/*
 * Copyright 2020 Andrey Tolpeev
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import teamcityapp.buildsrc.Config

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.google.firebase.crashlytics'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'com.google.android.gms.oss-licenses-plugin'
apply from: "$rootDir/scripts/jacoco.gradle"

android {
    namespace 'com.github.vase4kin.teamcityapp'

    defaultConfig {
        applicationId Config.applicationId
        versionCode Config.versionCode
        versionName Config.versionName
        vectorDrawables.useSupportLibrary = true
        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    signingConfigs {
        release {
            storeFile file(KEYSTORE_FILE)
            storePassword KEYSTORE_PASSWORD
            keyAlias KEY_ALIAS
            keyPassword KEY_PASSWORD
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            minifyEnabled true
        }
        debug {
            applicationIdSuffix = ".debug"
        }
    }

    flavorDimensions "default"

    productFlavors {
        mock {
            applicationIdSuffix = ".mock"
        }
        prod {

        }
    }

    android.variantFilter { variant ->
        if (variant.buildType.name == 'release'
                && variant.getFlavors().get(0).name == 'mock') {
            variant.setIgnore(true)
        }
    }

    packaging {
        resources {
            // Exclude AndroidX version files
            excludes += ['META-INF/*.version']
            // Exclude consumer proguard files
            excludes += ['META-INF/proguard/*']
            // Exclude the Firebase/Fabric/other random properties files
            excludes += ['/*.properties', 'fabric/*.properties', 'META-INF/*.properties']
            // More than one file was found with OS independent path 'META-INF/*.kotlin_module'
            excludes += ['META-INF/*.kotlin_module']
        }
    }

    // Fixing crash in androidTest
    // java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
    buildFeatures {
        buildConfig true
        dataBinding true
    }

    kotlinOptions {
        jvmTarget = Config.KotlinOptions.jvmTarget
    }

    testOptions {
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation projects.libraries.utils
    implementation projects.libraries.api
    implementation projects.libraries.resources
    implementation projects.libraries.theme
    implementation projects.libraries.chromeTabs
    implementation projects.libraries.storage
    implementation projects.libraries.storageModels
    implementation projects.libraries.cacheManager
    implementation projects.libraries.onboarding
    implementation projects.libraries.security
    implementation projects.libraries.remote

    implementation projects.features.testDetails.models
    implementation projects.features.testDetails.repository
    implementation projects.features.testDetails.feature

    implementation projects.features.splash

    implementation projects.features.about.models
    implementation projects.features.about.repository
    implementation projects.features.about.feature

    implementation projects.features.manageAccounts

    implementation projects.features.drawer

    implementation projects.features.settings

    implementation projects.features.changeDetails

    implementation projects.features.properties.models
    implementation projects.features.properties.feature

    // Android support libraries
    implementation libs.androidx.appcompat
    implementation libs.androidx.cardView
    implementation libs.androidx.legacySupport
    implementation libs.androidx.recyclerView
    implementation libs.androidx.preference
    implementation libs.google.material
    implementation libs.androidx.constraintLayout
    implementation libs.androidx.lifecycle.lifeCycle
    implementation libs.androidx.lifecycle.lifeCycleLiveData
    implementation libs.androidx.lifecycle.lifeCycleViewModel
    implementation libs.androidx.lifecycle.lifeCycleCommonJava8
    kapt libs.androidx.lifecycle.lifeCycleCompiler
    // Api third party libraries
    implementation libs.okhttp.okhttp
    implementation libs.okhttp.loggingInterceptor
    implementation libs.retrofit.retrofit
    implementation libs.retrofit.gsonConverter
    implementation libs.retrofit.retrofitRxjavaAdapter
    // Dialogs
    implementation libs.dialogs
    // Views
    implementation libs.errorView
    implementation libs.groupie.groupie
    // View injection
    implementation libs.butterknife.butterKnife
    annotationProcessor libs.butterknife.butterKnifeCompiler
    kapt libs.butterknife.butterKnifeCompiler
    // Event bus
    implementation libs.eventBus
    // Others
    implementation libs.jodaTime
    implementation libs.mugen
    implementation libs.shimmerlayout
    implementation libs.aboutLibrary
    // Onboarding
    implementation libs.materialTapTargetPrompt
    // Dagger
    implementation libs.dagger.dagger
    annotationProcessor libs.dagger.compiler
    kapt libs.dagger.compiler
    implementation libs.dagger.androidSupport
    annotationProcessor libs.dagger.androidProcessor
    kapt libs.dagger.androidProcessor
    // Rx
    implementation libs.rxjava.rxJava
    implementation libs.rxjava.rxAndroid
    implementation libs.rxjava.rxjava.kotlin
    // Rx cache
    implementation libs.rxcache.rxCache
    implementation libs.rxcache.jolyglot
    // Encryption
    implementation(libs.conceal) {
        artifact { type = 'aar' }
        transitive = false
    }
    // Firebase
    implementation libs.google.firebaseCore
    implementation libs.google.firebaseConfig
    implementation libs.google.firebasePerf
    implementation libs.google.openSourceLicensesLibrary
    // Bottom nav libries
    implementation libs.fragNav
    // Unit tests
    testImplementation libs.junit
    testImplementation libs.mockito.mockito3
    testImplementation libs.mockito.mockitoKotlin
    testImplementation libs.hamcrestJunit
    // Ui tests
    // Core library
    androidTestImplementation libs.androidx.test.core
    // AndroidJUnitRunner and JUnit Rules
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.androidx.test.rules
    androidTestUtil libs.androidx.test.orchestrator
    // Assertions
    androidTestImplementation libs.androidx.test.extJunit
    // Espresso dependenciesd
    androidTestImplementation libs.androidx.test.espresso.core
    androidTestImplementation libs.androidx.test.espresso.intents
    androidTestImplementation libs.androidx.test.espresso.contrib
    androidTestImplementation libs.androidx.test.espresso.web
    // Mockito
    androidTestImplementation libs.mockito.mockito3
    androidTestImplementation libs.mockito.mockitoKotlin
    // DexMaker Mockito support includes DexMaker transitively.
    androidTestImplementation libs.dexmaker.dexmakerMockito
    // Dagger mock
    androidTestImplementation libs.daggerMock
    // Resolve conflits between apks
    androidTestImplementation libs.google.material
    androidTestImplementation libs.androidx.recyclerView
    // Crashlytics
    implementation(libs.google.crashlytics)
    implementation(libs.google.analytics)

    implementation libs.kotlin.stdlib
}

apply plugin: 'com.google.gms.google-services'
