name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make it work
      run: |
        mkdir -p app/src/mock/debug/
        cp mock-mockDebug-google-services.json ./app/src/mock/debug/google-services.json
        mkdir -p app/src/prod/debug/
        cp mock-prodDebug-google-services.json ./app/src/prod/debug/google-services.json
    - name: Build with Gradle
      run: ./gradlew assembleDebug
