name: CI

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
        
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}
    
    - name: Copy google-services jsons
      run: |
        mkdir -p app/src/mock/debug/
        cp mock-mockDebug-google-services.json ./app/src/mock/debug/google-services.json
        mkdir -p app/src/prod/debug/
        cp mock-prodDebug-google-services.json ./app/src/prod/debug/google-services.json
    
    - name: Build app with gradle
      run: ./gradlew assembleDebug -Dorg.gradle.jvmargs=-Xmx1536m -Dorg.gradle.parallel=true -Dorg.gradle.daemon=false -Dorg.gradle.caching=false -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    
    - name: Upload build outputs
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: build-outputs
        path: app/build/outputs/
    
