name: CI

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.1.0
    
    - name: set up JDK 1.8
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 1.8
    
    - name: Copy google-services jsons
      run: |
        mkdir -p app/src/mock/debug/
        cp mock-mockDebug-google-services.json ./app/src/mock/debug/google-services.json
        mkdir -p app/src/prod/debug/
        cp mock-prodDebug-google-services.json ./app/src/prod/debug/google-services.json
    
    - name: Build app
      run: ./gradlew assembleProdDebug
    
    - name: Upload build outputs
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: build-outputs
        path: app/build/outputs
    
